<<<<<<< HEAD:target/classes/application.properties
spring.application.name=QuickServe
server.servlet.context-path=/quickserve
server.port=3030

spring.datasource.url=jdbc:mysql://localhost:3306/quickserve
spring.datasource.username=root
spring.datasource.password=password@123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

image.path.user=D:/QuickServe_Project/QuickServe/assets/user
image.path.provider.document=D:/QuickServe_Project/QuickServe/assets/provider/document
image.path.provider.certificate=D:/QuickServe_Project/QuickServe/assets/provider/certificate
image.path.provider.extraCertificate=D:/QuickServe_Project/QuickServe/assets/provider/certificate

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aiuseonly042@gmail.com
spring.mail.password=brjb iytn bhwu wiei
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.enabled=true
 spring.servlet.multipart.max-file-size=10MB
=======
spring.application.name=QuickServe
server.servlet.context-path=/quickserve
server.port=3030

spring.datasource.url=jdbc:mysql://localhost:3306/quickserve
spring.datasource.username=root
spring.datasource.password=password@123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

image.path.user=D:/QuickServe_Project/QuickServe/assets/user
image.path.provider.document=D:/QuickServe_Project/QuickServe/assets/provider/document
image.path.provider.certificate=D:/QuickServe_Project/QuickServe/assets/provider/certificate
image.path.provider.extraCertificate=D:/QuickServe_Project/QuickServe/assets/provider/certificate

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aiuseonly042@gmail.com
spring.mail.password=brjb iytn bhwu wiei
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.enabled=true
 spring.servlet.multipart.max-file-size=10MB
>>>>>>> 1f397e78fe7d03c75a79cdaf2ab5b9063b107290:Backend/src/main/resources/application.properties
 spring.servlet.multipart.max-request-size=20MB